# Generated by Django 4.2.13 on 2024-06-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
    ]
