# Generated by Django 4.2.13 on 2024-06-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_remove_employee_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
