# Generated by Django 3.1 on 2024-06-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240612_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photos/2024-06-05_10-05-53_profile.png', upload_to=''),
        ),
    ]
