# Generated by Django 4.2.14 on 2024-08-05 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_phone_profile_telegram_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bloger',
            field=models.BooleanField(default=False, verbose_name='bloger'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.BooleanField(default=False, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='p_photos/profile.png', upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='subscription_end'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True, default='', verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='translator',
            field=models.BooleanField(default=False, verbose_name='translator'),
        ),
    ]
