# Generated by Django 4.2.14 on 2024-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_follow_created_at_alter_save_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl', 'Dutch')], default='en-us', max_length=5),
        ),
    ]
