# Generated by Django 3.1 on 2024-06-06 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='anim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=255, unique=True)),
                ('name_farsi', models.CharField(max_length=255, unique=True)),
                ('name_Japanese', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('trailer', models.FileField(blank=True, upload_to='media/TR/')),
                ('photo', models.ImageField(default='media/photo/default.jpg', upload_to='')),
                ('status', models.CharField(choices=[('منتشر نشده', 'منتشر نشده'), ('در حال انتشار', 'در حال انتشار'), ('منتشر شده', 'منتشر شده')], max_length=13)),
                ('seasion', models.IntegerField(default=1)),
                ('max_episod', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='subscriptionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('subscripe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.subscriptionsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BestWeekAnim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.anim')),
            ],
        ),
        migrations.CreateModel(
            name='BestDayAnim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.anim')),
            ],
        ),
        migrations.CreateModel(
            name='anim_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('episod', models.IntegerField(default=1)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.anim')),
            ],
            options={
                'verbose_name_plural': 'episod',
                'ordering': ['episod'],
            },
        ),
        migrations.CreateModel(
            name='anim_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtile', models.FileField(upload_to='')),
                ('episod', models.IntegerField(default=1)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.anim')),
            ],
            options={
                'verbose_name_plural': 'subtiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
