# Generated by Django 3.1 on 2024-06-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0002_anim_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestweekanim',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='bestweekanim',
            name='anim',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='subscripe',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='BestDayAnim',
        ),
        migrations.DeleteModel(
            name='BestWeekAnim',
        ),
        migrations.DeleteModel(
            name='subscriptionModel',
        ),
        migrations.DeleteModel(
            name='subscriptionsModel',
        ),
    ]
