# Generated by Django 3.1 on 2024-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0003_auto_20240614_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='anim',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
