# Generated by Django 3.1 on 2024-06-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0004_anim_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anim',
            old_name='views',
            new_name='view',
        ),
    ]
