# Generated by Django 3.1 on 2024-06-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0005_auto_20240614_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anim',
            name='view',
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anim.anim')),
            ],
        ),
    ]
