# Generated by Django 5.0.6 on 2024-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0007_anim_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='anim_sub',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='anim_video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='view',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
