# Generated by Django 4.2.14 on 2024-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0008_alter_anim_id_alter_anim_sub_id_alter_anim_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anim_sub',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AlterField(
            model_name='anim_sub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='anim_sub',
            name='episod',
            field=models.IntegerField(default=1, verbose_name='episod'),
        ),
        migrations.AlterField(
            model_name='anim_sub',
            name='subtile',
            field=models.FileField(upload_to='', verbose_name='subtile'),
        ),
        migrations.AlterField(
            model_name='anim_video',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AlterField(
            model_name='anim_video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='anim_video',
            name='episod',
            field=models.IntegerField(default=1, verbose_name='episod'),
        ),
        migrations.AlterField(
            model_name='anim_video',
            name='video',
            field=models.FileField(upload_to='', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='view',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
